name: ci

on:
  push:
    branches:
    - main

env:
  ENABLE_VC_BUILD: 1
  directory: front

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: ${{env.directory}}
    steps:
    - name: ğŸ› Checkout
      uses: actions/checkout@v3
    - name: ğŸ® Make envfile
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_DATABASE_URL: ${{ secrets.DATABASE_URL }}
        directory: ${{env.directory}}
    - name: ğŸ”® Add pnpm
      run: npm install --global pnpm
    - name: âš¡ï¸ Install
      run: pnpm install
    - name: ğŸ›  Build
      run: pnpm build      
    - name: ğŸ›¸ Vercel
      uses: amondnet/vercel-action@v20
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-args: '--prod'
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
        working-directory: ${{env.directory}}
